# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c0fd543626e098b5f61133ae1cea59baf1d357c1db02dfe473f4ec42ab6cd23ebeb16ca47dc39e49d607790ef0cbbe9ff8d892f78cf128c8ce7ae5265a40c4

test:
  secret_key_base: 04a3b5284f2df98af788de0bb7416f1b9ecc55bc0ab93ef2ff939342cb6bd0dd85de87ecc06287901f576091f416146278e84eb50f4dc98017b33e265ce09fc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
